### PR TITLE
FIX Ensure media and embed TinyMCE plugin buttons are shown in the toolbar

### LINKED ISSUE #17: SilverStripe TinyMCE plugins are not showing in the toobar
For example, media and embed are not showing up:

CWP 2.0:

image

Vanilla SS4:

image

### PR DESCRIPTION
**Pull request by robbieaverill**
This pull request:

* Adds variable definitions into a closure (as other core \_config.php files do) to prevent creating global variables
* Adds the missing `insertButtonsAfter` calls for ssmedia and ssembed for the asset admin plugins (see `asset-admin/_config.php`)

Fixes #17

### CODE REVIEW

File: _config.php [hunk 1]
```diff
@@ -30,132 +30,137 @@
...
+        ->enablePlugins([
+            'ssmedia' => $assetAdminModule
+                ->getResource('client/dist/js/TinyMCE_ssmedia.js'),
+            'ssembed' => $assetAdminModule
+                ->getResource('client/dist/js/TinyMCE_ssembed.js'),
+            'sslinkfile' => $assetAdminModule
+                ->getResource('client/dist/js/TinyMCE_sslink-file.js'),
+        ]);
+    $cwpEditor->insertButtonsAfter('table', 'ssmedia');
+    $cwpEditor->insertButtonsAfter('ssmedia', 'ssembed');
```
Comment (robbieaverill) [inline _config.php]: These two lines are the additions
